### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/driving-game#1]
# Feature

User can see their car.

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create html and css for background 
- [x] Make sure page is mobile responsive
- [x] Place car on page
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## Example

This is just an example in case you need it.

![user can see their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-see-their-car.png)
