### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/driving-game#2]
# Feature

User can turn their car.

## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model: north, south, east, or west
- [x] Listen for 'keydown' events on the document
  - [x] Turn that guy
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## Example

This is just an example in case you need it.

![user can turn their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-turn-their-car.gif)
