### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/driving-game#3]
# Feature

User can start their car.

## Hints!

- Add a location to your data model to hold the car's `x` and `y` coordinates on the page.
- Use absolute positioning for your image.
- [Use the `style` property](https://developer.mozilla.org/en-US/docs/Web/API/ElementCSSInlineStyle/style) of element objects to change your car's `top` and `left` box offset styles.
- Move your car every `16` milliseconds for a smooth movement.
- The car doesn't have to change directions yet, that's a different feature.

## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's `x` and `y` coordinates on the page.
- [x] Use absolute positioning for your image
- [x] [Use the `style` property](https://developer.mozilla.org/en-US/docs/Web/API/ElementCSSInlineStyle/style) of element objects to change your car's `top` and `left` box offset styles.
- [ ] Move your car every `16` milliseconds for a smooth movement.
- [ ]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ]  Test all functionality again in a private browsing session.
- [ ]  Fix all errors.

## Example

This is just an example in case you need it.

![user can start their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-start-their-car.gif)
